### ISSUE TITLE
3.7.7, 3.7.8, 3.7.9 still not released

### ISSUE THREAD

**Issue by Akubi** [milesburton/Arduino-Temperature-Control-Library#104]
If you look Under Code relases, last released version still 3.7.6.
Idem under Tags.
So Code master is Up do Date but Tags are not Up do Date

**Comment by per1234** [comment]
This also means those versions are not available for installation via the Arduino Library Manager.
![clipboard01](https://user-images.githubusercontent.com/8572152/34981098-57cfa31e-fa5b-11e7-8e8d-b983c0a825bf.png)

**Comment by milesburton** [comment]
Done: https://github.com/milesburton/Arduino-Temperature-Control-Library/releases/tag/3.7.9
