### ISSUE TITLE
Function isConversionAvailable(sensor) is no longer part of library in version 3.7.9?

### ISSUE THREAD

**Issue by TobbeG** [milesburton/Arduino-Temperature-Control-Library#107]
In version 3.7.9 I can no longer use call **"sensors.isConversionAvailable(Sensor1)"** to test if
data are available.  Why have this been removed from previous version 3.7.6?
Best regards
Thorbjörn

**Comment by RobTillaart** [comment]
it is replaced by sensors.isConversionComplete(void).  The isConversionAvailable() function was not according to the datasheet, and could cause errors at certain temperatures.

relates to https://github.com/milesburton/Arduino-Temperature-Control-Library/issues/52
