### ISSUE TITLE
ESP32 compatibility

### ISSUE THREAD

**Issue by stickbreaker** [milesburton/Arduino-Temperature-Control-Library#109]
@milesburton I have made a version of the `OneWire` library at [stickbreaker/OneWire](https://github.com/stickbreaker/OneWire) that is compatible with the espressif/arduino-esp32.  It is based on a current fork of [PaulStroffregen/OneWire](https://github.com/PaulStoffregen/OneWire).  It uses conditional compile commands to maintain compatibility with the standard Arduino library and function correctly with the multi-tasking esp32.  

How extensive are the changes that you have incorporated into your version of the `OneWire` library included with your `DallasTemperature` library?

I would like be able to substitute my `OneWire` in place of your version.  Do you think that would be possible? 

I am trying to expand the esp32 compatible library list.

Chuck.

**Comment by milesburton** [comment]
Hi Chuck,

The intention is to remove OneWire from TCL - it slipped in a few months back. So once we've identified the differences, and what needs to be merged back into Paul's version TCL will be binary compatible. 

Paul is quite receptive so the best approach would be to raise a PR with him if you have new changes for OneWire
