### ISSUE TITLE
DallasTemperature::requestTemperaturesByAddress doesn't work in parasite power mode

### ISSUE THREAD

**Issue by pezinek** [milesburton/Arduino-Temperature-Control-Library#11]
According to specs of DS1822, if measuring temperature in parasite power mode the bus should be set high and keep it high until the temperature is ready, however the requestTemperaturesByAddress is calling isConnected in the mean time which breaks
the meassuring and keeps the sensor in undefined state.

Workarround could be to call isConnected before the STARTCONVO command is issued.

**Comment by pezinek** [comment]
Pull request #30 created for this issue. Sorry for the delay :-)

**Comment by wstrzalka** [comment]
It still didn't worked for me on ESP8266. With the trivial optimization (see pull request #40) it works.
Not really sure why but without the with the "strong pullup" is not there after CONVERT command

**Comment by pezinek** [comment]
Well this regression was actually caused during the of my pull request #30 with changes from pull request #10 (sorry for basing #30 on such an old parrent). The fix in #40 is actually correct and reverts to original behaviour from #30 and should be accepted IMO.
