### ISSUE TITLE
oneWireSearch.ino crashes

### ISSUE THREAD

**Issue by MattLogue** [milesburton/Arduino-Temperature-Control-Library#132]
Serial Mon:
//
// Start oneWireSearch.ino 
//
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400e9680: 00000000 ffffbf02 ffffffff
Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception)
Debug exception reason: Stack canary watchpoint triggered (loopTask) 
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)

**Comment by milesburton** [comment]
Can you provide more details? Platform, hardware etc. I'll close this for now
