### ISSUE TITLE
Is there a way to turn off the led blink?

### ISSUE THREAD

**Issue by deloosem** [milesburton/Arduino-Temperature-Control-Library#136]
Whenever I do a requestTemperatures a led blinks on my dev board.
Are we able to turn this off?

**Comment by RobTillaart** [comment]
Don't know, too little information.
Please note that problems with the devboard should be discussed on the Arduino forum or on a devboard specific forum. 

Do you have a schematic of the testboard?
If no, google for one, or order one at the supplier.
If yes, is the LED directly coupled to the dataline or powerline of the DS18B20?

**Comment by deloosem** [comment]
I just didn't think straight. The pin where the DS is connected is also the built-in led pin. D4. So it blinks when it requests or gets data. No big deal.
