### ISSUE TITLE
Getting error from line 436 from DallasTemperature.ccp

### ISSUE THREAD

**Issue by defpara** [milesburton/Arduino-Temperature-Control-Library#160]
As soon as I compile this fresh library in Arduino IDE it points to line 436: 10 error: 'yield' was not declared in this scope. yield();

ANything?

**Comment by RobTillaart** [comment]
yield() is a function that is used to let an (mini) OS interrupt in a blocking call. 

possible solutions
1. Update your Arduino IDE. (best )
2. add an empty function at top of sketch (worst)
```
void yield() {}; 
```

**Comment by defpara** [comment]
WOw that fast. THank u sir!

**Comment by RobTillaart** [comment]
@milesburton  please close

**Comment by RobTillaart** [comment]
@milesburton please close
