### ISSUE TITLE
 Error compiling for board NodeMCU 1.0 (ESP-12E Module)

### ISSUE THREAD

**Issue by mudassar791** [milesburton/Arduino-Temperature-Control-Library#161]
facing issue following error while compiling
Using library DallasTemperature-3.8.0 at version 3.8.0 in folder: C:\Program Files (x86)\Arduino\libraries\DallasTemperature-3.8.0 
Error
 Error compiling for board NodeMCU 1.0 (ESP-12E Module)

IDE1.8.12
NodeMCU Board Version 2.0.6
![Arduino](https://user-images.githubusercontent.com/32223328/79584663-21705780-80e8-11ea-92d9-d292b076ed16.png)

**Comment by RobTillaart** [comment]
Can you compile the example sketches that are provided with the library?

**Comment by castillo92** [comment]
No one is going to be able to help you if you do not show more code or expand the console panel to see what could happened.

**Comment by RobTillaart** [comment]
@milesburton 
As no more info in 35+ days the issue is probably solved, so it can be closed

**Comment by mudassar791** [comment]
solved,
