### ISSUE TITLE
Please issue a new release

### ISSUE THREAD

**Issue by dirkmueller** [milesburton/Arduino-Temperature-Control-Library#173]
The last published release tag is from 2018, and there's a great set of fixes in the master git branch only. Please consider planning and executing a new release so that dependent projects that typically pin their dependencies on a release version can benefit from these improvements.

**Comment by RobTillaart** [comment]
+ 1

**Comment by milesburton** [comment]
Done: https://github.com/milesburton/Arduino-Temperature-Control-Library/releases/tag/3.9.0

Though I need to add some release notes.
