### ISSUE TITLE
Yield function giving me an error

### ISSUE THREAD

**Issue by BitGrant** [milesburton/Arduino-Temperature-Control-Library#177]
Implemented this code with an Arduino UNO connected to a Raspberry pi 4 is giving me a Yield Error. 'Yield' was note declared in this scope.

**Comment by RobTillaart** [comment]
You should upgrade to the latest IDE. 
For the UNO yield() is implemented as an empty function.

**Comment by BitGrant** [comment]
You're exactly right. I was using it on Raspberry pi and the package I downloaded was old. Thank you!
