### ISSUE TITLE
Won't compile on Particle devices

### ISSUE THREAD

**Issue by karlg100** [milesburton/Arduino-Temperature-Control-Library#185]
Won't compile on particle devices due to yield() and WConstants.h fails.

added fix in patch set #183

**Comment by RobTillaart** [comment]
As I do not have particle experience / hardware I am not able to verify the particle specific changes by testing.
They look OK to me at first sight.

**Comment by karlg100** [comment]
Note that Particle.io forked a version of this library and hasn't updated in a while. (~Years) Hopefully this support back port will allow them to catch up on their published library collection.

**Comment by karlg100** [comment]
Will be supported starting in proposed version 3.10.0.
