### ISSUE TITLE
Keep getting -127.00

### ISSUE THREAD

**Issue by alaintanguy** [milesburton/Arduino-Temperature-Control-Library#201]
Arduino ESP32 on win10
I changed the sensor several times but still getting the error. The same sketch works on UNO:
Why is it not working on ESP32?
/*********
 https://randomnerdtutorials.com/esp32-ds18b20-temperature-arduino-ide/O parasitic connection: Center (data) to 4.7KOhms To +3.3V 
									2 pins left and right to Ground 
									Data to GPIO 4 ESP32 Wroom
*********/
#include <DallasTemperature.h>//vers 3.9.0
#include <OneWire.h>

// GPIO where the DS18B20 is connected to
const int oneWireBus = 4;  //ESP32 Wroom   

// Setup a oneWire instance to communicate with any OneWire devices
OneWire oneWire(oneWireBus);

// Pass our oneWire reference to Dallas Temperature sensor 
DallasTemperature sensors(&oneWire);
void setup() {
  // Start the Serial Monitor
  Serial.begin(115200);
  // Start the DS18B20 sensor
  sensors.begin();
}
void loop() {
  sensors.requestTemperatures(); 
  float temperatureC = sensors.getTempCByIndex(0);
  delay(1000);
  if(temperatureC == -127.00){
	Serial.println("Failed to read from DS18B20 sensor");
  } else{
	Serial.print(temperatureC);
	Serial.println("ºC");	
   }	
  delay(3000);
}

**Comment by brammittendorff** [comment]
We use the board of:
https://quinled.info/2018/09/15/quinled-dig-uno/

With both chips `ESP32` and `ESP8266`. Then with the library WLED:
https://github.com/Aircoookie/WLED

With usermod:
https://github.com/Aircoookie/WLED/tree/master/usermods/Temperature

We tried WLED v0.12.0 and up until v0.13.0-b2. When using ESP8266 it just reads the temperature well:
![0c525ecd-9076-4829-b2a7-9d602d9fd641](https://user-images.githubusercontent.com/7221583/129184900-8e99ce66-cbcc-4362-adbe-cffc971c9b87.jpg)

When we switch to `ESP32` the result always is:
```C
      if (temperature <= -100.0 || (!sensorFound && temperature == -1.0)) {
        temp.add(0);
        temp.add(F(" Sensor Error!"));
        return;
      }
```

And when we change the code to see the temperature in:
```C
      if (temperature <= -100.0 || (!sensorFound && temperature == -1.0)) {
        temp.add(temperature );
        temp.add(F(" Sensor Error!"));
        return;
      }
```

With `ESP32` it always reads `-127`.

We tried 4 boards and all with the same result. Is there something broken with this library regarding `ESP32` ?
