### ISSUE TITLE
Disconnected sensor messes up sensor indices

### ISSUE THREAD

**Issue by janifr** [milesburton/Arduino-Temperature-Control-Library#226]
Disconnecting sensor 0 on 2 sensor system causes sensor 1 to return value -127 and sensor 0 return temperature of sensor 1 making data useless.

**Comment by milesburton** [comment]
This is expected behavior. If you need consistency because you are
disconnecting ICs, you'll need to use the getByAddress function

**Comment by janifr** [comment]
Thank you for super fast response! Could you please point me an example how to use the getByAddress function?

**Comment by milesburton** [comment]
See line 51 and go from there: https://github.com/milesburton/Arduino-Temperature-Control-Library/blob/master/examples/Multiple/Multiple.ino

**Comment by janifr** [comment]
Thanks, problem solved. If anyone's interested, my code is here: https://github.com/janifr/esp8266_dallastemperature_aws_iot
