### ISSUE TITLE
Additional documentation website cannot be reached

### ISSUE THREAD

**Issue by RobTillaart** [milesburton/Arduino-Temperature-Control-Library#241]
https://www.milesburton.com/w/index.php/Dallas_Temperature_Control_Library

gives an 523 error - (DNS problem CLoudfare message) while I can reach the site with a ping command.

Something serious or are am I not patient enough?

**Comment by RobTillaart** [comment]
Closed as there is no action

**Comment by milesburton** [comment]
Apologies I was away for Christmas and my server decided it didn't want to serve. Thanks for the heads up Rob
