### ISSUE TITLE
Arduino nano esp32 not findiding DS18B20

### ISSUE THREAD

**Issue by AngelRionCervi** [milesburton/Arduino-Temperature-Control-Library#246]
Using an arduino nano esp32, I always get -127 as a result with the `Simple.ino` example.
I tried with some resistors, 1K and 4.7K, even then it's on a breadboard so the cables are very short. 
I also tried with 5V and 3V3, same result.

No issues with a XIAO ESP32C3 or uno R4 WIFI.

**Comment by RobTillaart** [comment]
(No experience with the NANO ESP32)
Which pins of the NANO did you use for data pin? 
Have you tried others?  
Some of the pins might have additional functions already causing problems.
(Had a pin problem with another ESP32 when trying some software SPI, so this could be similar).

**Comment by AngelRionCervi** [comment]
Ok it seems I wrote this issue a bit too fast.

I used the the variable names (A0 for example) instead of the GPIO number (1 in this case).
If I use the GPIO numbers from the pinout diagram, it all works fine:
<img width="195" alt="Screenshot 2023-08-29 at 20 55 05" src="https://github.com/milesburton/Arduino-Temperature-Control-Library/assets/34657288/81b92115-e6df-4e31-8d1f-264884771d14">

Thank you !
