### ISSUE TITLE
Does not work on low temperatures, always show -127C

### ISSUE THREAD

**Issue by Nalorokk** [milesburton/Arduino-Temperature-Control-Library#27]

**Comment by milesburton** [comment]
Can you confirm which version (commit) you are using from Git. This was actually recently resolved

**Comment by Nalorokk** [comment]
Still exists for me in latest commit 146cfdd2d7

**Comment by RobTillaart** [comment]
@Nalorokk 
Does this problem still exist? otherwise this issue can be closed.

**Comment by milesburton** [comment]
I believe this is actually still outstanding. https://github.com/milesburton/Arduino-Temperature-Control-Library/tree/tommi-tuovila-temperature-fix resolved the issue but I don't believe it was ever confirmed by the author so I opted to avoid merging.

Are you able to test this in your setup and let us know if it works. If it does, it'll be quick merge

**Comment by milesburton** [comment]
Closing, assuming not a problem

**Comment by rubberduck203** [comment]
I know it's an old issue, but I'm actually experiencing this problem with a MAX31820.
Does anyone remember the cause or solution?

**Comment by rubberduck203** [comment]
This happens if you wire VDD and GND backwards.
The pinout in the datasheet for the MAX31820 is wrong.

<img width="711" alt="screen shot 2017-10-16 at 8 31 19 pm" src="https://user-images.githubusercontent.com/2716800/31641271-8169fa5e-b2b1-11e7-95a5-9f3287b72cee.png">
