### ISSUE TITLE
Version at 3.7.2 or 3.7.4?

### ISSUE THREAD

**Issue by mvhconsult** [milesburton/Arduino-Temperature-Control-Library#42]
You released these versions, but the code still uses older ones. Which one is correct?

**Comment by milesburton** [comment]
I'm about to bump the version shortly and get all version to align. Please bare with me (but to answer your question 3.7.4)

**Comment by PaoloP74** [comment]
Latest release is 3.7.5, but library manager install version 3.7.2. Bug?

**Comment by milesburton** [comment]
Slightly more worryingly it's not showing up at all for me in the library listings. I'll have to give it a go on my laptop with a fresh install
