### ISSUE TITLE
double readScratchPad() in DallasTemperature::begin()

### ISSUE THREAD

**Issue by assafYavnai** [milesburton/Arduino-Temperature-Control-Library#48]
in version 3.7.1 in DallasTemperature::begin()

There are the following lines (DallasTemperature.cpp:56-60):

//**scratchPad is never actually used**
ScratchPad scratchPad;
readScratchPad(deviceAddress, scratchPad);  
//**here getResolution() reads scratchPad again internally....**
bitResolution = max(bitResolution, getResolution(deviceAddress));

recommendation:
remove the following unused, double called code from method
ScratchPad scratchPad;
readScratchPad(deviceAddress, scratchPad);

**Comment by RobTillaart** [comment]
Had a quick look and seems to be a correct observation

**Comment by milesburton** [comment]
Agreed. Corrected
