### ISSUE TITLE
What is meant by conversion?

### ISSUE THREAD

**Issue by jamesrobb** [milesburton/Arduino-Temperature-Control-Library#59]
Hello,

I have been reading through the source code, and I can't seem to make sense of what conversion means. Does it simply refer to a celcius to fahrenheit conversion, or something else?

**Comment by RobTillaart** [comment]
At the heart of the DS18B20 is an ADC - AnalogDigitalConversion - which measures the temperature as a voltage or current (analog) . This analog value is **converted** to a digital value (bits) and the more accurate bits you want the more time it takes. Roughly the time doubles for every additional bit (in its working range). This is also known as the **conversion time**.

**Comment by jamesrobb** [comment]
Thanks!
