### ISSUE TITLE
Error on reboot 

### ISSUE THREAD

**Issue by rally7** [milesburton/Arduino-Temperature-Control-Library#64]
I have a Pro Micro ATmega32U4 (Leonardo) that has a simple sketch that simply reads the temp from A DS18B20.  The sketch uploads and runs fine the first time printing out the correct temp until you restart or reset the Arduino.  Then the temp prints out as -196.60  I have tried multiple sensors with the same result. 

The DS18B20 is connected Red to +5v, Black to Ground and Yellow (signal) is connected to Red by 4.7K resistor and to pin 6 on the Mini.

Thanks for any help!

Bill
# include <DallasTemperature.h>
# include <OneWire.h>

OneWire oneWire(6);
DallasTemperature sensors(&oneWire);

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  Serial.println("Program Start");

   //initialized temp sensors
  sensors.begin();

}

void loop() {
  // put your main code here, to run repeatedly:

  sensors.requestTemperatures();
  float temp;
  temp = sensors.getTempFByIndex(0);
  Serial.print("Now sending ");
  Serial.println(temp);

} 
UPDATE 8/30/16:
If I ground pins 1 and 3 (VCC and GND) as recommended I immediately get the -196.60
I have tried this with 2 different processors with the same results.

**Comment by MarkVeldt** [comment]
Hi Bill,

You have to wait for the conversion to be finished, see the WaitForConversion examples at the end of the code for more explanations.

Also -196.6 is defined in the header file that should also give a hint.
(#define DEVICE_DISCONNECTED_F -196.6)

In parasitic mode the function requestTemperatures() always returns directly.

Happy programming.

**Comment by RobTillaart** [comment]
@rally7 
Is this issue still valid?

**Comment by milesburton** [comment]
Please reopen if this is still an issue. I presume you've solved it during the last year ;)
