### ISSUE TITLE
DS18B20 reading with non blocking

### ISSUE THREAD

**Issue by SayedBaqer** [milesburton/Arduino-Temperature-Control-Library#65]
is there any way to use this library as non blocking, where i need to avoid delay in the arduino sketch where i am beginner in programing ?
Best regards,

**Comment by RobTillaart** [comment]
Yes, the example sketches include an asynchronous version.. 
Still you need to keep track of the timing somewhere

**Comment by RobTillaart** [comment]
@milesburton 
Please close
