### ISSUE TITLE
Compiling in INO environment (command-line Arduino dev)

### ISSUE THREAD

**Issue by marcusj** [milesburton/Arduino-Temperature-Control-Library#66]
I had some problems compiling the cpp code within the ino environment and had to explicitly cast out some of the const specifications.  Diff:

`79c72
## <     return (_wire->crc8(deviceAddress, 7) == deviceAddress[7]);

> ```
> return (_wire->crc8((unsigned char*)deviceAddress, 7) == deviceAddress[7]);
> ```
> 
> 121c114
> ## <     _wire->select(deviceAddress);
> 
> ```
> _wire->select((unsigned char*)deviceAddress);
> ```
> 
> 149c142
> ## <     _wire->select(deviceAddress);
> 
> ```
> _wire->select((unsigned char*)deviceAddress);
> ```
> 
> 160c153
> ## <     _wire->select(deviceAddress);
> 
> ```
> _wire->select((unsigned char*)deviceAddress);
> ```
> 
> 173c166
> ## <     _wire->select(deviceAddress);
> 
> ```
> _wire->select((unsigned char*)deviceAddress);
> ```
> 
> 353c346
> ## <     _wire->select(deviceAddress);
> 
> ```
> _wire->select((unsigned char*)deviceAddress);
> ```
> 
> 834c827
> `

**Comment by milesburton** [comment]
Thanks, I'll take a look

**Comment by Patroklo** [comment]
For noobs like me, if you are having right now errors compiling INO (for example with the Arduino IDE) files with this library, change the extension of the file to .PDE and it will work fine.

**Comment by RobTillaart** [comment]
@marcusj 
Is this issue still valid?

**Comment by milesburton** [comment]
As per @RobTillaart, reopen if this is still an issue
