### ISSUE TITLE
#define CONFIGURATION conflicts with other libraries

### ISSUE THREAD

**Issue by Nzbuu** [milesburton/Arduino-Temperature-Control-Library#71]
```
#define CONFIGURATION   4
```

conflicts with other libraries that use the same string "CONFIGURATION" in other places. For example: in https://github.com/marvinroger/homie-esp8266/blob/develop/src/HomieBootMode.hpp, CONFIGURATION is part of an enumeration.

Leads to compiler errors such as: "error: expected identifier before numeric constant".

**Comment by milesburton** [comment]
Good spot. We should name space this.

**Comment by Nzbuu** [comment]
Is there a good reason why the scratchpad locations need to be in the header file? Would it be better to just move them into the source file? Under what circumstances would any other module need to use the scratchpad locations?

I can do this and raise a pull request, if you like.

**Comment by milesburton** [comment]
Go ahead @Nzbuu
