### ISSUE TITLE
getTempByAddress (v3.5) missing

### ISSUE THREAD

**Issue by haaxema** [milesburton/Arduino-Temperature-Control-Library#73]
Hi all,

Am I missing out on something? I cant find any reference in the code for the function getTempByAddress (added in 3.5).

It is a feature that I would like to use in some of my code.

Am I looking in the wrong direction or is it removed in versions beyond 3.5?

Martin

**Comment by RobTillaart** [comment]
@haaxema 
The functions named **getTempC(address)**  and **getTempF(address)** allready fetch the name by address. I will create a pull request to change the readme.

(Sorry for late reply)

**Comment by RobTillaart** [comment]
@milesburton 
Explained in readme, can be closed
