### ISSUE TITLE
Why the temperature from DS18B20 by using the library is always zero？

### ISSUE THREAD

**Issue by zhoufusong** [milesburton/Arduino-Temperature-Control-Library#74]
@milesburton @SaintGimp @chrwei @RobTillaart @Ducatel 
Why the temperature from DS18B20 by using the library is always zero？ hope your reply.

I just use this method from this article:http://www.arduino.cn/thread-1345-1-1.html

**Comment by jiapei100** [comment]
Same here... 
In my case,  **sensors.getDeviceCount()** always returns 0 .

Cheers
Pei

**Comment by RobTillaart** [comment]
Do you have a pull up resistor on the dataline? e.g. 4K7 between +5V and dataline.
 If not the communication is less reliable (longer wire length needs smaller resistor).
Do you have a proper 5Volt? please check with a voltmeter.

**Comment by RobTillaart** [comment]
@zhoufusong   Sorry cannot read the link you posted, but schematic looks ok.

**Comment by RobTillaart** [comment]
@milesburton 
There is no reaction from the "questioneers" so apparently the problems are solved,
please close

**Comment by Spreeuw** [comment]
I have the same issue, and I don't quite understand why:
`
  numberOfDevices = sensors.getDeviceCount(); // returns 0
  numberOfDevices = 3;
  for (int i = 0; i < numberOfDevices; i++) {
    if (sensors.getAddress(tempDeviceAddress, i)) {
      sensors.setResolution(tempDeviceAddress, TEMPERATURE_PRECISION);
    }
  }
`
so `sensors.getDeviceCount()` returns 0 yet I can setResolution and do `sensors.requestTemperatures()` and `sensors.getTempCByIndex(i)` without problems. Any ideas? I do this on an ESP32 (Lolin D32 Pro), so not sure if this is somehow related to #114

**Comment by chrwei** [comment]
this issue about the temperature returning zero, not the number of devices.  you should make a new issue,
