### ISSUE TITLE
requestTemperatures() blocks until one sensor is ready not all of them

### ISSUE THREAD

**Issue by bschick** [milesburton/Arduino-Temperature-Control-Library#79]
Docs imply that requestTemperatures will block until conversion is complete. I have 4 sensors (mix of MAX31820 and DS18B20) on a single 1 wire channel and was noticing frequent failures. Digging into this library, it looks like isConversionComplete returns when one of the sensors is ready rather than all of them. If there is any difference in conversion times between the sensors, subsequent getTemp calls can fail.

I've changed checkForConversion to false to workaround the problem, but either the docs and comments should be updated to be clear that requestTemperatures doesn't check for all sensors to complete or code enhanced to check all known sensors.

**Comment by milesburton** [comment]
Hmm, interesting spot. Thanks for the report. We'll look into it
