### ISSUE TITLE
int16_t DallasTemperature::millisToWaitForConversion(uint8_t)' is private

### ISSUE THREAD

**Issue by jeffersonpenteado** [milesburton/Arduino-Temperature-Control-Library#86]
Whenever I try to compile this message it appears, Can someone help?

arduino 1.8.3
dallas temperature 3.7.6
onewire 2.3.3

**Comment by RobTillaart** [comment]
Which code are you trying to compile? For which hardware platform?

**Comment by mfalkvidd** [comment]
Related to https://github.com/milesburton/Arduino-Temperature-Control-Library/pull/72

**Comment by Akubi** [comment]
Version 3.7.7 is available but Arduino still look for wersion 3.7.6 ???

**Comment by mfalkvidd** [comment]
@Akubi 3.7.6 is the latest release according to https://github.com/milesburton/Arduino-Temperature-Control-Library/releases

**Comment by Akubi** [comment]
Yes sure. But the source version on master is the 3.7.7
Version 3.7.7 (master) solve the #72 issue, but on release we still have the 3.7.6

**Comment by mfalkvidd** [comment]
@Akubi the Arduino IDE only looks for released versions.

**Comment by Akubi** [comment]
Yes this is the problem. Why do not put the last version as released ?

**Comment by milesburton** [comment]
Fixed it latest release
