### ISSUE TITLE
Reading problem / sensor sensitivity

### ISSUE THREAD

**Issue by lazarvgd** [milesburton/Arduino-Temperature-Control-Library#88]
Hi, I am using this library and I have observed that it has very good precision. The problem is occurring if I heat sensor up with hand and then release it to cool down to room's temperature, it takes about 7-10 mins.

For example, I have heated up to 30 deg. C with hand and measured time until sensor reads 26 deg. C. The time was ~10min.

Can you please tell me is this normal or I am doing something wrong? With code from question #87  I got instant measurements after releasing the sensor and leave it to room temperature.

thanks

EDIT:

If it is necessary I can post my code snippet.

**Comment by RobTillaart** [comment]
There are different ds18b20 bodies (> 10) which all have a different heat capacity as the different sizes have more or less mass causing some latency when heating up / cooling down. E.g. the watertight reacts slower than the "normal" one as the watertight enclosure also works as isolation.  check the [datasheet](https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf) if it mentions details.

The speed of cooling depends on the difference in temperature of the environment and the temperature of the sensor itself. You can see this if you plot the values of a cooling down / heat up in a graph.

**Comment by lazarvgd** [comment]
Thanks Rob. Sorry about this question.
